defaults:
    sample_data: 'none'
    source: 'ros'
    qos_profile:
        reliability: 'reliable'
        history: 'keep_last'
        durability: 'volatile'
        depth: 1

topics:

  - topic_name: '/string_topic'
    msg_type: 'std_msgs/msg/String'
    sample_data: 'random'

  - topic_name: '/bool_topic'
    msg_type: 'std_msgs/msg/Bool'
    sample_data: 'random'

  - topic_name: '/int_topic'
    msg_type: 'std_msgs/msg/Integer'
    sample_data: 'random'
