defaults:
    sample_data: 'none'
    sample_rate: 1
    source: 'ros'
    qos_profile:
        reliability: 'reliable'
        history: 'keep_last'
        durability: 'volatile'
        depth: 1

topics:

  - topic_name: '/gnss/filtered'
    msg_type: 'sensor_msgs/msgs/NavSatFix'

  - topic_name: '/goal_pose_gnss'
    msg_type: 'sensor_msgs/msgs/NavSatFix'
    source: 'serial'
